### ISSUE TITLE
Fail to install snorkel v0.9

### ISSUE THREAD

**Issue by s2948044** [snorkel-team/snorkel#1410]
## Issue description

IDK if the update of v0.9 is completed or still undergoing, but I tried installing it with all ways but with no success.

## Code example/repro steps

1. install with `pip install -U .`
```
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  Complete output from command C:\ProgramData\Anaconda3\python.exe C:\ProgramData\Anaconda3\lib\site-packages\pip\_vendor\pep517\_in_process.py get_requires_for_build_wheel C:\Users\ADMINI~1\AppData\Local\Temp\tmphg30k5qs:
  Traceback (most recent call last):
    File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 207, in <module>
      main()
    File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-env-flyzxagw\overlay\Lib\site-packages\setuptools\build_meta.py", line 146, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-env-flyzxagw\overlay\Lib\site-packages\setuptools\build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-env-flyzxagw\overlay\Lib\site-packages\setuptools\build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 13, in <module>
      long_description = readme_file.read()
  UnicodeDecodeError: 'gbk' codec can't decode byte 0x94 in position 3169: illegal multibyte sequence

  ----------------------------------------
```
2. install with `pip install snorkel`
```
Collecting snorkel
  Could not find a version that satisfies the requirement snorkel (from versions: )
No matching distribution found for snorkel
```

## Expected behavior

Install sucessfully.

## System info

* How you installed Snorkel (conda, pip, source): No
* Build command you used (if compiling from source):
* OS: Windows 10
* Python version: 3
* Snorkel version: N/A
* Versions of any other relevant libraries: N/A

**Comment by henryre** [comment]
Hi @s2948044, glad you're eager to try out the new version! We're still in the middle of the release, so we'll circle back tomorrow. We haven't done much testing on Windows, so happy to work together to get this resolved.

**Comment by s2948044** [comment]
I think the problem with Windows is that the default encoding is `gbk` instead of `utf-8`, so explicitly declare the encoding when reading files should solve the problem.

**Comment by henryre** [comment]
@s2948044 we've updated our PyPI package, so are you able to get things working with `pip install snorkel`? There shouldn't be any encoding issues related to setup.py.

**Comment by s2948044** [comment]
@henryre  Hi, it now works with `pip install`, thanks.
