### ISSUE TITLE
Operator names not unique: 2 operators with name check

### ISSUE THREAD

**Issue by linonetwo** [snorkel-team/snorkel#1548]
## Issue description

I'm trying to load rule from config file, and generate labeling function on the fly, but I get: `ValueError: Operator names not unique: 2 operators with name check`

## Code example/repro steps

`ruleMatch` is my function that parses rule and generates a parser.

```python
from typing import List
from snorkel.labeling import labeling_function, PandasLFApplier, LFAnalysis

def getLabelingFunctions(rules: List[str]):
  labelingFunctions = []
  for rule in rules:
    @labeling_function()
    def check(x):
      return SPAM if ruleMatch(rule, x.text.lower()) else ABSTAIN
    labelingFunctions.append(check)
  return labelingFunctions

applier = PandasLFApplier(lfs=getLabelingFunctions(["$ * check $ *", "$ * check out $ *"]))
```

```
Traceback (most recent call last):
  File "/xxx/checkRuleCoverage.py", line 27, in <module>
    applier = PandasLFApplier(lfs=getLabelingFunctions(["$ * check $ *", "$ * check out $ *"]))
  File "/opt/anaconda3/envs/TensorFSARNN/lib/python3.6/site-packages/snorkel/labeling/apply/core.py", line 38, in __init__
    check_unique_names(self._lf_names)
  File "/opt/anaconda3/envs/TensorFSARNN/lib/python3.6/site-packages/snorkel/utils/data_operators.py", line 9, in check_unique_names
    raise ValueError(f"Operator names not unique: {ct} operators with name {k}")
ValueError: Operator names not unique: 2 operators with name check
```

## Expected behavior

We can use dynamic generated labeling functions

## System info

* How you installed Snorkel (conda, pip, source): conda
* OS: Mac 10.15.3
* Python version: 3.6
* Snorkel version: snorkel==0.9.3
* Versions of any other relevant libraries: pytorch==1.1.0

**Comment by linonetwo** [comment]
I know, I can passing name=:

```python
@labeling_function(name=rule)
    def check(x):
      return SPAM if ruleMatch(rule, x.text.lower()) else ABSTAIN
    labelingFunctions.append(check)
```

**Comment by linonetwo** [comment]
If I do so, there will not be an error, but all things will be checked by the last labeling function, the previous one will be overwritten by the last function, result in all `[True, True]` or `[False, False]`, identical result.

**Comment by linonetwo** [comment]
Oh, it is due to closure, this can be solved by using IIFE:

```python
def getLabelingFunctions(rules: List[str]):
    labelingFunctions = []
    for rule in rules:
        # use iife to prevent classical closure stale value problem
        def IIFE(rule: str):
            @labeling_function(name=rule)
            def checkRuleCoversText(row: Series):
                # make sure pandas row contains value, it sometimes just being None
                if len(row.values) == 0:
                    return False
                text = row.values[0]
                if text == None:
                    return False
                # now use the rule to check text
                return True if dfaFromRule(rule).execute(text) else False

            labelingFunctions.append(checkRuleCoversText)

        IIFE(rule)
    return labelingFunctions
```
